### ISSUE TITLE
Filter missing for UDP?

### ISSUE THREAD

**Issue by Mr-Tea-Baggins** [amwalding/wireshark_profiles#3]
Should  there not be a filter for UDP packets?

**Comment by amwalding** [comment]
It depends.  Which profile are you referring to?

**Comment by Mr-Tea-Baggins** [comment]
My apologies - I mean a UDP specific profile.

(thank you for your other profiles; some seriously great work you have shared here)!.

**Comment by amwalding** [comment]
There is a UDP profile.

**Comment by amwalding** [comment]
I just updated the one that was lurking here.  It was old.  Let me know what you would add/change/delete

**Comment by Mr-Tea-Baggins** [comment]
Great stuff ! Thank you very much.
Awesome work Andrew :)

**Comment by Mr-Tea-Baggins** [comment]
UDP profile available
