### ISSUE TITLE
IP6 Default profile issue (field is identified as a label)

### ISSUE THREAD

**Issue by Mr-Tea-Baggins** [amwalding/wireshark_profiles#4]
Hi Andrew - 

![error](https://github.com/user-attachments/assets/22f109d6-5828-4d72-9f85-86cbb59a038a)

When switching to the 'IP6 Default' profile I get the attached error message.  I tried removing the ==1 after "bad ", but seems a little more complex for me to debug.

I am using Wireshark 4.4.0 on Linux Pop OS.

Not in anyway a urgent issue, but IP6 profiles are becoming more and more important.  Thank you.

**Comment by amwalding** [comment]
Yes - this is a color filter issue.  The error is not terminal in that Wireshark simply disables the color rule in question.  For some reason this error exists in all the IPv6 profiles.  I have corrected them and updated them.

**Comment by Mr-Tea-Baggins** [comment]
Awesome, thank you Andrew.  So quick!
Great work - thank you
